name = 'mini-midi-magic-2'
providers = ['node']

[variables]
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
dependsOn = ['setup']
cmds = ['cd site && npm ci']

[phases.build]
dependsOn = ['install'] 
cmds = ['cd site && npm run build']

[start]
cmd = 'cd site && npm start'